# -*- coding: utf-8 -*-
"""Currency Converter .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZIC14i2t5jlFvpaGOA8-FAGLM_Wu3CC
"""

# This is a code cell

rates = {
    "USD": 1.0,
    "EUR": 0.92,
    "GBP": 0.79,
    "JPY": 150.25,
    "NGN": 1500.00
}

print("Available currencies:")
for currency in rates:
    print(currency)

from_currency = input("Convert from: ").upper()
to_currency = input("Convert to: ").upper()
amount = float(input("Amount: "))

if from_currency not in rates or to_currency not in rates:
    print("Invalid currency selection.")
else:
    amount_in_usd = amount / rates[from_currency]
    converted_amount = amount_in_usd * rates[to_currency]
    print(f"{amount} {from_currency} = {converted_amount:.2f} {to_currency}")